from .resources import *
def initialize_routes(api):
    api.add_resource(AdminLoginApi,'/api/adminlogin')
    api.add_resource(registerTrainer,'/api/registerTrainer')
    api.add_resource(trainerLoginApi,'/api/trainerlogin')
    api.add_resource(registerTrainee,'/api/registerTrainee')
    api.add_resource(traineeLoginApi,'/api/traineelogin')
    api.add_resource(removeTrainer,'/api/removeTrainer')
    api.add_resource(removeTrainee, '/api/removeTrainee')
    api.add_resource(trainerImages, '/api/trainerImages')
    api.add_resource(trainerVideos, '/api/trainerVideos')
    api.add_resource(selectTrainer, '/api/selectTrainer/<email>')
    api.add_resource(getTrainer, '/api/getTrainer/<email>')
    api.add_resource(equipmentsApi, '/api/equipments')
    api.add_resource(equipmentApi, '/api/equipment/<name>')
    api.add_resource(foodSuplementsApi, '/api/foodSuplementsApi')
    api.add_resource(foodSuplementApi, '/api/foodSuplementApi/<name>')
    api.add_resource(placeorderEquipments, '/api/placeorderEquipments/<orderName>')
    api.add_resource(placeorderFoodSupplements, '/api/placeorderFoodSupplements/<orderName>')
